//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserId { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string Job { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public string FavoriteBook { get; set; }
        public string FavoriteMusic { get; set; }
        public int Constellation { get; set; }
    
        public virtual Types Types { get; set; }
        public virtual Users Users { get; set; }
    }
}
