//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Log = new HashSet<Log>();
            this.MessageBoard = new HashSet<MessageBoard>();
            this.MessageBoard1 = new HashSet<MessageBoard>();
        }
    
        public int id { get; set; }
        public string UserLoginName { get; set; }
        public string UserLoginPwd { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<MessageBoard> MessageBoard { get; set; }
        public virtual ICollection<MessageBoard> MessageBoard1 { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
